version = 1

test_patterns = [
  "__tests__/**",
  "test_*.py"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "jest",
    "browser",
    "nodejs",
    "mongo"
  ]
  plugins = ["react"]
  style_guide = "airbnb"
  dialect = "typescript"


[[transformers]]
name = "prettier"
enabled = true
